### ISSUE TITLE
All wireless devices gone since version 0.5.0

### ISSUE THREAD

**Issue by nrenner73** [kingsleyadam/local-abbfreeathome-hass#16]
After updating to version 0.5.0 all the previously detected devices became unavailable.
I tried deleting the integration and do a complete reinstall.

Now I only have the system access point as a device and no switches anymore.

Is that somehow related to closed issue #8 ?

Thanks!

**Comment by kingsleyadam** [comment]
We added device filtering so it's possible your devices got filtered out. Do you have hired wired bus devices? Or another type of device?

You can downgrade to the previous version in HACS and it should come back online. I'd probably need a list of devices as it comes from the API to know if the filtering was the issue.

If possible you can do this with the example code here: https://github.com/kingsleyadam/local-abbfreeathome?tab=readme-ov-file#get-configuration

**Comment by kingsleyadam** [comment]
The PR related to filtering is #14

**Comment by nrenner73** [comment]
I only have wireless devices so far. Where can I set up the filtering?

Thanks!

**Comment by derjoerg** [comment]
@nrenner73 : The filtering is hard-coded in the integration. So first we need to find out what is the interface-name of your wireless switches and afterwards the library and this integration needs to be upgraded.

So, if you can get the configuration as explained above by @kingsleyadam and - if possible - also provide the serial-number of the wireless switch it should be easily adaptable.

**Comment by kingsleyadam** [comment]
@nrenner73 , I've just pushed out a new version 0.5.1 that'll add a new "Action" to developer tools. It's device dump (see screenshot). When you run this you'll get your list of devices. Search for "interface" and let us know what you have and we can get it added.

Developer Tools -> Actions

<img width="1223" alt="Screenshot 2024-10-11 at 13 51 41" src="https://github.com/user-attachments/assets/5cd05f75-3e3c-4f16-affb-1419b936945c">

**Comment by nrenner73** [comment]
Thanks for the new version @kingsleyadam 
The interface for the wireless devices is `RF`
Here is an example:
`    "ABB7F6318851": {
      "deviceReboots": "13",
      "floor": "03",
      "room": "0E",
      "interface": "RF",`

**Comment by kingsleyadam** [comment]
@nrenner73 , I just pushed a new release with this interface included. Can you give this one a try?

**Comment by kingsleyadam** [comment]
> Can confirm, all wireless devices are back with version 0.5.2
> 
> Thanks!

NIce! And thanks for trying out the integration, it's still super early but I'm glad it's working for you.
