### ISSUE TITLE
Add support for dimmer switches

### ISSUE THREAD

**Issue by nrenner73** [kingsleyadam/local-abbfreeathome-hass#23]
Maybe it´s too early, but I wanted to ask if support for dimmer switches can be implemented. 

I digged through your code and I think I get it, but it would help me a lot if I could compare the necessary code for a second device type to the already implemented switch_actuator.

Anyway, attached is the config of a dimming actuator downloaded from the swagger ui of my SysAP.

```
{
  "00000000-0000-0000-0000-000000000000": {
    "devices": {
      "ABB7F630A832": {
        "deviceReboots": "22",
        "floor": "02",
        "room": "02",
        "interface": "RF",
        "deviceId": "2039",
        "displayName": "Esszimmer Tisch",
        "unresponsive": false,
        "unresponsiveCounter": 0,
        "defect": false,
        "channels": {
          "ch0000": {
            "floor": "02",
            "room": "02",
            "displayName": "Esszimmer Tisch",
            "functionID": "1",
            "inputs": {
              "idp0000": {
                "pairingID": 256,
                "value": "0"
              },
              "idp0001": {
                "pairingID": 18,
                "value": "0"
              },
              "idp0002": {
                "pairingID": 273,
                "value": "0"
              },
              "idp0004": {
                "pairingID": 261,
                "value": "0"
              },
              "idp0005": {
                "pairingID": 278,
                "value": "0"
              },
              "idp0009": {
                "pairingID": 272,
                "value": "0"
              },
              "idp000a": {
                "pairingID": 277,
                "value": "0"
              }
            },
            "outputs": {
              "odp0000": {
                "pairingID": 1,
                "value": "0"
              },
              "odp0001": {
                "pairingID": 16,
                "value": "8"
              },
              "odp0006": {
                "pairingID": 4,
                "value": "0"
              }
            },
            "parameters": {
              "par0002": "30",
              "par0001": "50",
              "par0007": "1"
            }
          },
          "ch0008": {
            "floor": "02",
            "room": "02",
            "displayName": "Esszimmer Tisch",
            "selectedIcon": "1",
            "functionID": "12",
            "inputs": {
              "idp0000": {
                "pairingID": 1,
                "value": "0"
              },
              "idp0001": {
                "pairingID": 16,
                "value": "8"
              },
              "idp0002": {
                "pairingID": 17,
                "value": "0"
              },
              "idp0003": {
                "pairingID": 2,
                "value": "0"
              },
              "idp0004": {
                "pairingID": 3,
                "value": "0"
              },
              "idp0005": {
                "pairingID": 4,
                "value": "0"
              },
              "idp0006": {
                "pairingID": 18,
                "value": "0"
              },
              "idp0007": {
                "pairingID": 6,
                "value": "0"
              }
            },
            "outputs": {
              "odp0000": {
                "pairingID": 256,
                "value": "0"
              },
              "odp0001": {
                "pairingID": 272,
                "value": "0"
              },
              "odp0002": {
                "pairingID": 273,
                "value": "0"
              },
              "odp0003": {
                "pairingID": 257,
                "value": "0"
              }
            },
            "parameters": {
              "par0013": "3",
              "par0004": "20",
              "par0005": "100",
              "par0012": "100",
              "par0015": "60",
              "par0029": "2"
            }
          },
          "ch000b": {
            "floor": "02",
            "room": "02",
            "displayName": "Esszimmer Tisch",
            "functionID": "1",
            "inputs": {
              "idp0000": {
                "pairingID": 256,
                "value": "0"
              },
              "idp0001": {
                "pairingID": 272,
                "value": "0"
              },
              "idp0006": {
                "pairingID": 261,
                "value": "0"
              },
              "idp0007": {
                "pairingID": 277,
                "value": "0"
              }
            },
            "outputs": {
              "odp0000": {
                "pairingID": 1,
                "value": "0"
              },
              "odp0001": {
                "pairingID": 16,
                "value": "0"
              }
            },
            "parameters": {
              "par0010": "1"
            }
          }
        },
        "parameters": {
          "par00ed": "1"
        }
      }
    }
  }
}
```

**Comment by kingsleyadam** [comment]
> Maybe it´s too early, but I wanted to ask if support for dimmer switches can be implemented.
> 
> I digged through your code and I think I get it, but it would help me a lot if I could compare the necessary code for a second device type to the already implemented switch_actuator.
> 
> Anyway, attached is the config of a dimming actuator downloaded from the swagger ui of my SysAP.
> 
> ```
> {
>   "00000000-0000-0000-0000-000000000000": {
>     "devices": {
>       "ABB7F630A832": {
>         "deviceReboots": "22",
>         "floor": "02",
>         "room": "02",
>         "interface": "RF",
>         "deviceId": "2039",
>         "displayName": "Esszimmer Tisch",
>         "unresponsive": false,
>         "unresponsiveCounter": 0,
>         "defect": false,
>         "channels": {
>           "ch0000": {
>             "floor": "02",
>             "room": "02",
>             "displayName": "Esszimmer Tisch",
>             "functionID": "1",
>             "inputs": {
>               "idp0000": {
>                 "pairingID": 256,
>                 "value": "0"
>               },
>               "idp0001": {
>                 "pairingID": 18,
>                 "value": "0"
>               },
>               "idp0002": {
>                 "pairingID": 273,
>                 "value": "0"
>               },
>               "idp0004": {
>                 "pairingID": 261,
>                 "value": "0"
>               },
>               "idp0005": {
>                 "pairingID": 278,
>                 "value": "0"
>               },
>               "idp0009": {
>                 "pairingID": 272,
>                 "value": "0"
>               },
>               "idp000a": {
>                 "pairingID": 277,
>                 "value": "0"
>               }
>             },
>             "outputs": {
>               "odp0000": {
>                 "pairingID": 1,
>                 "value": "0"
>               },
>               "odp0001": {
>                 "pairingID": 16,
>                 "value": "8"
>               },
>               "odp0006": {
>                 "pairingID": 4,
>                 "value": "0"
>               }
>             },
>             "parameters": {
>               "par0002": "30",
>               "par0001": "50",
>               "par0007": "1"
>             }
>           },
>           "ch0008": {
>             "floor": "02",
>             "room": "02",
>             "displayName": "Esszimmer Tisch",
>             "selectedIcon": "1",
>             "functionID": "12",
>             "inputs": {
>               "idp0000": {
>                 "pairingID": 1,
>                 "value": "0"
>               },
>               "idp0001": {
>                 "pairingID": 16,
>                 "value": "8"
>               },
>               "idp0002": {
>                 "pairingID": 17,
>                 "value": "0"
>               },
>               "idp0003": {
>                 "pairingID": 2,
>                 "value": "0"
>               },
>               "idp0004": {
>                 "pairingID": 3,
>                 "value": "0"
>               },
>               "idp0005": {
>                 "pairingID": 4,
>                 "value": "0"
>               },
>               "idp0006": {
>                 "pairingID": 18,
>                 "value": "0"
>               },
>               "idp0007": {
>                 "pairingID": 6,
>                 "value": "0"
>               }
>             },
>             "outputs": {
>               "odp0000": {
>                 "pairingID": 256,
>                 "value": "0"
>               },
>               "odp0001": {
>                 "pairingID": 272,
>                 "value": "0"
>               },
>               "odp0002": {
>                 "pairingID": 273,
>                 "value": "0"
>               },
>               "odp0003": {
>                 "pairingID": 257,
>                 "value": "0"
>               }
>             },
>             "parameters": {
>               "par0013": "3",
>               "par0004": "20",
>               "par0005": "100",
>               "par0012": "100",
>               "par0015": "60",
>               "par0029": "2"
>             }
>           },
>           "ch000b": {
>             "floor": "02",
>             "room": "02",
>             "displayName": "Esszimmer Tisch",
>             "functionID": "1",
>             "inputs": {
>               "idp0000": {
>                 "pairingID": 256,
>                 "value": "0"
>               },
>               "idp0001": {
>                 "pairingID": 272,
>                 "value": "0"
>               },
>               "idp0006": {
>                 "pairingID": 261,
>                 "value": "0"
>               },
>               "idp0007": {
>                 "pairingID": 277,
>                 "value": "0"
>               }
>             },
>             "outputs": {
>               "odp0000": {
>                 "pairingID": 1,
>                 "value": "0"
>               },
>               "odp0001": {
>                 "pairingID": 16,
>                 "value": "0"
>               }
>             },
>             "parameters": {
>               "par0010": "1"
>             }
>           }
>         },
>         "parameters": {
>           "par00ed": "1"
>         }
>       }
>     }
>   }
> }
> ```

@nrenner73 , can you post this again with the dimmer's actually turned on? By looking at this I _think_ the dimmers are off, so I just want to double check what it looks like when they're on.

**Comment by nrenner73** [comment]
Ok, here´s the dimmer in full throttle (100% on)

```
{
  "00000000-0000-0000-0000-000000000000": {
    "devices": {
      "ABB7F630A832": {
        "deviceReboots": "22",
        "floor": "02",
        "room": "02",
        "interface": "RF",
        "deviceId": "2039",
        "displayName": "Esszimmer Tisch",
        "unresponsive": false,
        "unresponsiveCounter": 0,
        "defect": false,
        "channels": {
          "ch0000": {
            "floor": "02",
            "room": "02",
            "displayName": "Esszimmer Tisch",
            "functionID": "1",
            "inputs": {
              "idp0000": {
                "pairingID": 256,
                "value": "1"
              },
              "idp0001": {
                "pairingID": 18,
                "value": "1"
              },
              "idp0002": {
                "pairingID": 273,
                "value": "0"
              },
              "idp0004": {
                "pairingID": 261,
                "value": "0"
              },
              "idp0005": {
                "pairingID": 278,
                "value": "0"
              },
              "idp0009": {
                "pairingID": 272,
                "value": "100"
              },
              "idp000a": {
                "pairingID": 277,
                "value": "0"
              }
            },
            "outputs": {
              "odp0000": {
                "pairingID": 1,
                "value": "1"
              },
              "odp0001": {
                "pairingID": 16,
                "value": "0"
              },
              "odp0006": {
                "pairingID": 4,
                "value": "0"
              }
            },
            "parameters": {
              "par0002": "30",
              "par0001": "50",
              "par0007": "1"
            }
          },
          "ch0008": {
            "floor": "02",
            "room": "02",
            "displayName": "Esszimmer Tisch",
            "selectedIcon": "1",
            "functionID": "12",
            "inputs": {
              "idp0000": {
                "pairingID": 1,
                "value": "1"
              },
              "idp0001": {
                "pairingID": 16,
                "value": "0"
              },
              "idp0002": {
                "pairingID": 17,
                "value": "100"
              },
              "idp0003": {
                "pairingID": 2,
                "value": "0"
              },
              "idp0004": {
                "pairingID": 3,
                "value": "0"
              },
              "idp0005": {
                "pairingID": 4,
                "value": "0"
              },
              "idp0006": {
                "pairingID": 18,
                "value": "1"
              },
              "idp0007": {
                "pairingID": 6,
                "value": "0"
              }
            },
            "outputs": {
              "odp0000": {
                "pairingID": 256,
                "value": "1"
              },
              "odp0001": {
                "pairingID": 272,
                "value": "100"
              },
              "odp0002": {
                "pairingID": 273,
                "value": "0"
              },
              "odp0003": {
                "pairingID": 257,
                "value": "0"
              }
            },
            "parameters": {
              "par0013": "3",
              "par0004": "20",
              "par0005": "100",
              "par0012": "100",
              "par0015": "60",
              "par0029": "2"
            }
          },
          "ch000b": {
            "floor": "02",
            "room": "02",
            "displayName": "Esszimmer Tisch",
            "functionID": "1",
            "inputs": {
              "idp0000": {
                "pairingID": 256,
                "value": "0"
              },
              "idp0001": {
                "pairingID": 272,
                "value": "0"
              },
              "idp0006": {
                "pairingID": 261,
                "value": "0"
              },
              "idp0007": {
                "pairingID": 277,
                "value": "0"
              }
            },
            "outputs": {
              "odp0000": {
                "pairingID": 1,
                "value": "0"
              },
              "odp0001": {
                "pairingID": 16,
                "value": "0"
              }
            },
            "parameters": {
              "par0010": "1"
            }
          }
        },
        "parameters": {
          "par00ed": "1"
        }
      }
    }
  }
}
```

**Comment by kingsleyadam** [comment]
@derjoerg and @nrenner73 , I've created a PR to add the light entity. I have absolutely no way to test this, I don't have dimmers in my house.

If both of you could pull these changes in manually and test and report back that'd be great.

https://github.com/kingsleyadam/local-abbfreeathome-hass/pull/38/files

**Comment by derjoerg** [comment]
I should be able to test this tonight

**Comment by nrenner73** [comment]
Will give it a test tonight, thanks!

**Comment by nrenner73** [comment]
I was able to change/create the files, but after a restart I see the following in the log:

```
Logger: homeassistant.components.light
Quelle: helpers/entity_platform.py:369
Integration: Leuchte (Dokumentation, Probleme)
Erstmals aufgetreten: 15:47:17 (2 Vorkommnisse)
Zuletzt protokolliert: 15:47:44

Error while setting up abbfreeathome_ci platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 369, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 628, in async_add_entities
    for entity in new_entities:
  File "/config/custom_components/abbfreeathome_ci/light.py", line 34, in <genexpr>
    FreeAtHomeLightEntity(light, sysap_serial_number=entry.data[CONF_SERIAL])
  File "/config/custom_components/abbfreeathome_ci/light.py", line 50, in __init__
    self.entity_description = LightEntityDescription(
                              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/frozen_dataclass_compat.py", line 120, in __new__
    return cls._dataclass(*_args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LightEntityDescription.__init__() missing 1 required positional argument: 'key'
```

Did I forget to add something here?

**Comment by derjoerg** [comment]
> TypeError: LightEntityDescription.__init__() missing 1 required positional argument: 'key'
> ```
> 
> Did I forget to add something here?

Same here

**Comment by kingsleyadam** [comment]
Can you try again? I missed adding a param to the entity description.

https://github.com/kingsleyadam/local-abbfreeathome-hass/pull/38/commits/b036fa38cd52504f69b7d54d67319f7191bdd647

**Comment by derjoerg** [comment]
Working now for me!

PERFECT

**Comment by nrenner73** [comment]
Working for me, too!
Errors in the log are gone, 3 new devices found, switching on/off and dimming works as expected.

Only thing I noticed is that the dimming actuators do not show a value for the model in the integration´s device overview. It just reads <unknown>. But this is only a cosmetic issue.

![image](https://github.com/user-attachments/assets/ec0286e4-a737-4dea-a9ce-c10e47974179)

**Comment by kingsleyadam** [comment]
> Working for me, too! Errors in the log are gone, 3 new devices found, switching on/off and dimming works as expected.
> 
> Only thing I noticed is that the dimming actuators do not show a value for the model in the integration´s device overview. It just reads 'unknown'. But this is only a cosmetic issue.
> 
> ![image](https://private-user-images.githubusercontent.com/71392216/378900450-ec0286e4-a737-4dea-a9ce-c10e47974179.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MTAyODgsIm5iZiI6MTcyOTYwOTk4OCwicGF0aCI6Ii83MTM5MjIxNi8zNzg5MDA0NTAtZWMwMjg2ZTQtYTczNy00ZGVhLWE5Y2UtYzEwZTQ3OTc0MTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE1MTMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNDlhZWVhZGIzNTI3YmM4YzcyY2RlZDBiOGRjYzVjYzM5MmI1YTQyYTNjZTg3NDRlYjM4NTExYjk1NWJiYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EVuqKXVGCSmfoqpYcqsjsAZUM3xBCwJ-bOK9XWaaHIc)

That's correct, officially the Free@Home local api doesn't actually expose a model number for each device. Original I setup the Switch's to use a set string `SwitchingActuator` but I've decided to remove that as that's more a function of a channel, then an actual model of the device.

I do wish we could get the actual model number of each device, but it's just not there.

@derjoerg @nrenner73 , and just to confirm a few things.

- Dimming works properly? When you set dimmer to e.g. 80% in Home Assistant it's relfected the same in the ABB Free@Home App?
- From an off state, just setting the dimming value in Home Assistant turns on the device and dims it to the correct value?

Thanks for your help!

**Comment by nrenner73** [comment]
> > Working for me, too! Errors in the log are gone, 3 new devices found, switching on/off and dimming works as expected.
> 
> > 
> 
> > Only thing I noticed is that the dimming actuators do not show a value for the model in the integration´s device overview. It just reads 'unknown'. But this is only a cosmetic issue.
> 
> > 
> 
> > ![image](https://private-user-images.githubusercontent.com/71392216/378900450-ec0286e4-a737-4dea-a9ce-c10e47974179.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MTAyODgsIm5iZiI6MTcyOTYwOTk4OCwicGF0aCI6Ii83MTM5MjIxNi8zNzg5MDA0NTAtZWMwMjg2ZTQtYTczNy00ZGVhLWE5Y2UtYzEwZTQ3OTc0MTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE1MTMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNDlhZWVhZGIzNTI3YmM4YzcyY2RlZDBiOGRjYzVjYzM5MmI1YTQyYTNjZTg3NDRlYjM4NTExYjk1NWJiYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EVuqKXVGCSmfoqpYcqsjsAZUM3xBCwJ-bOK9XWaaHIc)
> 
> 
> 
> That's correct, officially the Free@Home local api doesn't actually expose a model number for each device. Originally I setup the Switch's to use a set string `SwitchingActuator` but I've decided to remove that as that's more a function of a channel, then an actual model of the device.
> 
> 
> 
> I do wish we could get the actual model number of each device, but it's just not there.
> 
> 
> 
> @derjoerg @nrenner73 , and just to confirm a few things.
> 
> 
> 
> - Dimming works properly? When you set dimmer to e.g. 80% in Home Assistant it's relfected the same in the ABB Free@Home App?
> 
> - From an off state, just setting the dimming value in Home Assistant turns on the device and dims it to the correct value?
> 
> 
> 
> Thanks for your help!

I did a clean install of the integration and noticed that now most of the model descriptions are gone. Ok for me. 

I can confirm that the brightness between the Free@Home App and Home Assistant is synchronized quite quickly.
So yes, when I change the brightness in one App it is reflected in the other. 

It even recognizes the minimum brightness I have set up in Free@Home, meaning I cannot go below the set minimum in HA, which is perfect. 

And yes, from an off state, switching the device on by setting a brightness is possible. 

Awesome!
