### ISSUE TITLE
MovementDetectors without brightness

### ISSUE THREAD

**Issue by derjoerg** [kingsleyadam/local-abbfreeathome-hass#27]
Hi,
I just discovered that I have two different kind of MovementDetectors installed in my F@H setup.
So there are the indoor detectors, which act as configured with motion and brightness.

But I also have outdoor detectors (same functionID!!!), which don't have brightness...
```
          "ch0000": {
            "floor": "02",
            "room": "0E",
            "displayName": "Bewegung Vorne",
            "selectedIcon": "52",
            "functionID": "11",    FID_MOVEMENET_DETECTOR
            "inputs": {},
            "outputs": {
              "odp000d": {
                "pairingID": 6,    AL_TIMED_MOVEMENT
                "value": "0"
              }
            },
            "parameters": {
              "par0010": "1"    PID_BI_CONTACT_TYPE
            }
          },
```
And for them I get the following error in HA-log:
```
Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:595
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 17:06:06 (4 Vorkommnisse)
Zuletzt protokolliert: 17:06:06

Error adding entity sensor.binary_input_4gang_mdrc_illuminance for domain sensor with platform abbfreeathome_ci
Error adding entity sensor.binary_input_4gang_mdrc_illuminance_2 for domain sensor with platform abbfreeathome_ci
Error adding entity sensor.binary_input_4gang_mdrc_illuminance_3 for domain sensor with platform abbfreeathome_ci
Error adding entity sensor.binary_input_4gang_mdrc_illuminance_4 for domain sensor with platform abbfreeathome_ci
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 595, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 909, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 542, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/abbfreeathome_ci/sensor.py", line 121, in native_value
    return getattr(self._device, self._value_attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/abbfreeathome/devices/movement_detector.py", line 53, in brightness
    return float(self._brightness)
                 ^^^^^^^^^^^^^^^^
AttributeError: 'MovementDetector' object has no attribute '_brightness'. Did you mean: 'brightness'?
```

Does this needs to be handled in the HA-component or in the library?

**Comment by kingsleyadam** [comment]
I was wondering if this scenario would ever come-up. In the PyPi library we can probably add a new attribute to the Base class that includes the states that are available based on the outputs provided by Free@Home. And in Home Assistant do a verification if e.g. brightness exists as a state before adding the sensor.

**Comment by derjoerg** [comment]
As I'm still not such a python-programmer like you I would let you decide on the complexity of the implementation.
Nevertheless, I can only say that this is the only case I know so far with different settings within the same functionID. So perhaps for now your second option might be easier and doesn't add too much overhead for all the other classes.

If - in the future - more and more devices would come up with such a behaviour it can still be reworked.

**Comment by kingsleyadam** [comment]
> @kingsleyadam Just thinking loud: If moving the "_refresh_state_pairings" from the function "refresh_state" to the base-class (e.g. something like "_state_pairings_input" and "_state_pairings_output") it wouldn't be that much overhead as the configuration can be re-used

Nice idea, I've made a number of refactors in this PR: https://github.com/kingsleyadam/local-abbfreeathome/pull/53

Hopefully it all makes sense, goal is to ensure all devices states have an initial value so we don't get an exception `object has no attribute` (this will allow us to fix this exception you had above in this integration), and reduce duplicate code

**Comment by kingsleyadam** [comment]
@derjoerg , I just pushed out a new version to fix this scenario, let me know if it's not working as it should.

**Comment by derjoerg** [comment]
Nice, this is working now as expected 😃 
I see another issue with the naming, but I will address this in a separate issue
