### ISSUE TITLE
Add RoomTemperatureController as Climate entity

### ISSUE THREAD

**Issue by kingsleyadam** [kingsleyadam/local-abbfreeathome-hass#71]
### Discussed in https://github.com/kingsleyadam/local-abbfreeathome-hass/discussions/70

<div type='discussions-op-text'>

<sup>Originally posted by **rernst** November  9, 2024</sup>
Hi,

Thanks for the awesome work on this integration! I just installed it in a dev container and everything seems to work smoothly. 

The only device I am missing is a 'RoomTemperatureController'. [local-abbfreeathome](https://github.com/kingsleyadam/local-abbfreeathome) seems to have support for it since last week. So I was just wondering if someone (@derjoerg ?) is working on implementing this as a climate entity?

If not I might try to implement it my self (or help/test if needed), just have to find some time for it :).

Thanks again for the awesome work. 

Cheers,
Robert</div>

**Comment by derjoerg** [comment]
@rernst, @nrenner73

Can you try to test this PR in your setup?

**Comment by nrenner73** [comment]
No errors in the log and I have a new device for each of my thermostats.

![2024-11-12](https://github.com/user-attachments/assets/59ff7e37-52ba-4126-a0be-77dc03c32b7c)

![2024-11-12 (1)](https://github.com/user-attachments/assets/ae295e64-4862-45d2-8f0c-bb4e019afbaf)

Changes of settings (temperature, on/off/eco) on the device are updatet in HA and the other way round works too. 
And wow, this is quick!

Let me play with it a bit more but this already looks like another piece of amazing work. Thank you!

**Comment by rernst** [comment]
Nice work, thanks! Everything seems to work (no errors in log) and my thermostat is automatically added and controllable.
